name: EPGs

permissions:
  contents: write

on:
  push:
    tags:
      - "epgs-*"
  workflow_dispatch: {}
  schedule:
    - cron: '2 */4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update
        run: bash epgs.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Tag
        id: tag
        run: |
          if git diff --quiet --exit-code
          then
              TAG=epgs-$(date +%s)
              echo "$TAG"
              echo "tag=$TAG" >> $GITHUB_OUTPUT
              git tag $TAG
              git push origin $TAG
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.tag != ''
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: ./*.xml.gz
          body: 'Autoupdate'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean
        uses: jay2610/delete-older-releases@1.0.0
        with:
          keep_latest: 2
          delete_tag_pattern: epgs
          delete_type: 'release'
          target_branch: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
