name: EPGs

permissions:
  contents: write

on:
  schedule:
    - cron: '2 */4 * * *'
  workflow_dispatch: {}
  push:
    tags:
      - "epgs-*"


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update
        run: bash epgs.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

#       - name: Commit and push
#         run: |
#           git config --global user.name "github-actions[bot]"
#           git config --global user.email "github-actions[bot]@users.noreply.github.com"
#           if git diff --quiet --exit-code
#           then
#               echo "No changes to commit."
#               exit 0
#           fi
#           git add EPG_LITE.xml.gz
#           git commit -m "Autoupdate $(date +%s)"
#           git push --force origin HEAD:master

      - name: Tag
        id: tag
        run: |
          if git diff --quiet --exit-code
          then
              TAG=list_$(date +%s)
              echo "$TAG"
              echo "tag=$TAG" >> $GITHUB_OUTPUT
              git tag $TAG
              git push origin $TAG
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: ./*.xml.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean
        uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 5
          keep-old-minor-releases: false
