name: LIST

permissions:
  contents: write

on:
  push:
    tags:
      - "list-*"
  workflow_dispatch: {}
  schedule:
    - cron: '1 1 * * 1'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update
        run: bash list.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Push
        id: push
        run: |
          ls -la
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet --exit-code
          then
              echo "No changes to commit."
              echo "proceed=false" >> $GITHUB_OUTPUT
              exit 0
          fi
          git add list
          printf "Autoupdate\n\n" | cat - diff > diff.tmp
          mv diff.tmp diff
          git commit -F diff
          git push origin HEAD:master
          echo "proceed=true" >> $GITHUB_OUTPUT

      - name: Tag
        id: tag
        if: steps.push.outputs.proceed == 'true'
        run: |
          TAG=list_$(date +%s)
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag $TAG
          git push origin $TAG

      - name: Release
        if: steps.push.outputs.proceed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            ./list
            ./diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean
        uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 5
          keep-old-minor-releases: false
